services:

  server:
    build: ./Server
    ports:
      - 8080:8080
    environment:
    - ASPNETCORE_HTTP_PORTS=8080

  client:
    build: ./Client
    network_mode: host
    depends_on:
      - server
    environment:
      - SERVER_URL=ws://localhost:8080